<?php

/**
 * @file
 * School module file for overriding functionality.
 */


/*
 * Implements hook_toolbar_alter()
 */
function school_toolbar_alter(&$items) {
  $items['administration']['#attached']['library'][] = 'school/toolbar-icon';

  // Remove the "Back to site" button from toolbar.
  unset($items['home']);
}


/**
 * Implements hook_form_alter().
 */
function school_form_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(\Drupal\school\Controller\SchoolFormAlter::class)
    ->alterForm($form, $form_state, $form_id);
}

