name: xsmind
recipe: drupal9
config:
  webroot: .
  drush: ^11
  xdebug: true
  php: '8.1'
  conf:
    php: lando/php.ini

services:
  appserver:
    xdebug: true
    overrides:
      environment:
        # Support debugging with XDEBUG 3.
        XDEBUG_MODE: debug
        # Support debugging Drush with XDEBUG 3.
        PHP_IDE_CONFIG: "serverName=xsmind.lndo.site"
        # Specific Xdebug Configs
        LANDO_HOST_IP: "host.docker.internal"
        XDEBUG_CONFIG: "remote_enable=1 remote_host=host.docker.internal"
    config:
      php: lando/php.ini
  phpmyadmin:
    type: phpmyadmin
  database:
    run_as_root:
      # Assign permission databases.
      - mysql -uroot -e "GRANT SUPER ON *.* to 'drupal9'@'%' IDENTIFIED by 'drupal9';"

tooling:
  build-site:
    service:
      appserver:
    description: "Rebuild Xsmind App"
    cmd:
      - appserver: ./scripts/site-build.sh
