name: xsmind
recipe: drupal9
config:
  webroot: .
  drush: ^11

tooling:
  build-site:
    service:
      appserver:
    description: "Rebuild Xsmind App"
    cmd:
      - appserver: ./scripts/site-build.sh
services:
  myservice:
    type: phpmyadmin
