name: xsmind
recipe: drupal10
config:
  webroot: .
  drush: ^12
  xdebug: true
  php: '8.1'
  conf:
    php: lando/php.ini

services:
  appserver:
    xdebug: true
    overrides:
      environment:
        # Support debugging with XDEBUG 3.
        XDEBUG_MODE: debug
        # Support debugging Drush with XDEBUG 3.
        PHP_IDE_CONFIG: "serverName=xsmind.lndo.site"
        # Specific Xdebug Configs
        LANDO_HOST_IP: "host.docker.internal"
        XDEBUG_CONFIG: "remote_enable=1 remote_host=host.docker.internal"
    config:
      php: lando/php.ini
  phpmyadmin:
    type: phpmyadmin
  database:
    run_as_root:
      # Assign permission databases.
      - mysql -uroot -e "GRANT SUPER ON *.* to 'drupal10'@'%' IDENTIFIED by 'drupal10';"

tooling:
  build-site:
    service:
      appserver:
    description: "Rebuild Xsmind App"
    cmd:
      - appserver: ./scripts/site-build.sh

  windrush:
    service: appserver
    description: Run drush in Windows host OS
    cmd: php /app/vendor/drush/drush/drush

  xdebug-on:
    service: appserver
    description: Enable Xdebug.
    user: root
    cmd:
      - docker-php-ext-enable xdebug && kill -USR2 $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 2 && echo "Xdebug On" && tput sgr 0 && echo

  xdebug-off:
    service: appserver
    description: Disable Xdebug.
    user: root
    cmd:
      - rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && kill -USR2 $(pgrep -o php-fpm) > /dev/null || /etc/init.d/apache2 reload
      - tput setaf 1 && echo "Xdebug Off" && tput sgr 0 && echo
