<?php

/**
 * @file
 * organisation module file for overriding functionality.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function organisation_theme($existing, $type, $theme, $path) {

  return [
    'organisationview' => [
      'variables' => ['data' => NULL],
    ],
  ];
}

/**
 * Implements hook_preprocess_image_widget().
 */
function organisation_preprocess_image_widget(&$variables) {
  $element = $variables['element'];

  $variables['attributes'] = [
    'class' => [
      'image-widget', 'js-form-managed-file', 'form-managed-file', 'clearfix',
    ],
  ];

  if (!empty($element['fids']['#value'])) {
    $file = reset($element['#files']);
    $element['file_' . $file->id()]['filename']['#suffix'] = ' <span class="file-size">(' . format_size($file->getSize()) . ')</span> ';
    $file_variables = [
      'style_name' => $element['#preview_image_style'],
      'uri' => $file->getFileUri(),
    ];

    // Determine image dimensions.
    if (isset($element['#value']['width']) && isset($element['#value']['height'])) {
      $file_variables['width'] = $element['#value']['width'];
      $file_variables['height'] = $element['#value']['height'];
    }
    else {
      $image = \Drupal::service('image.factory')->get($file->getFileUri());
      if ($image->isValid()) {
        $file_variables['width'] = $image->getWidth();
        $file_variables['height'] = $image->getHeight();
      }
      else {
        $file_variables['width'] = $file_variables['height'] = NULL;
      }
    }

    $element['preview'] = [
      '#weight' => -10,
      '#theme' => 'image_style',
      '#width' => $file_variables['width'],
      '#height' => $file_variables['height'],
      '#style_name' => $file_variables['style_name'],
      '#uri' => $file_variables['uri'],
    ];

    // Store the dimensions in the form so the file doesn't have to be
    // accessed again. This is important for remote files.
    $element['width'] = [
      '#type' => 'hidden',
      '#value' => $file_variables['width'],
    ];
    $element['height'] = [
      '#type' => 'hidden',
      '#value' => $file_variables['height'],
    ];
  }

  $variables['data'] = [];
  foreach (Element::children($element) as $child) {
    $variables['data'][$child] = $element[$child];
  }
}

/**
 * Implements hook_views_pre_render().
 */
function organisation_views_pre_render($view) {

  $encrypt = \Drupal::service('encrypt.service');

  $result = $view->result;
  foreach ($result as $i => $row) {
   // $encrypted_codepk = $encrypt->encode($view->result[$i]->codepk);
   // $view->result[$i]->srch_view_codevalues_description = $encrypted_codepk;
  }
}
