<?php
/**
 * Implementation of hook_theme_suggestions_form_element_alter().
 */
/* function employee_theme_suggestions_form_element_alter(array &$suggestions, array $variables) {

  if (\Drupal::service('path.current')->getPath() == '/employee/add/academics') {
    $suggestions[] = $variables['theme_hook_original'] . '--multistep-form-three';
  }
}
 */
/**
 * Implementation of hook_preprocess_form_element().
 */
/*
function employee_preprocess_form_element(&$variables, $hook, &$info) {
	if (\Drupal::service('path.current')->getPath() == '/employee/add/academics') {
  $info['template'] = 'form-element--multistep-form-three';
	}
}*/

function employee_theme($existing, $type, $theme, $path) {

  return array(
    'employee-profile' => array(
      'variables' => array('data' => NULL),
    ),
  );
}
