# Schema for the views entity reference selection plugins.

entity_reference_selection.dependent_fields_selection:
  type: mapping
  label: 'Make field dependent using views handler settings'
  mapping:
    dependent_fields_view:
      type: mapping
      label: 'View used to select the entities'
      mapping:
        view_name:
          type: string
          label: 'View name'
        display_name:
          type: string
          label: 'Display name'
        parent_field:
          type: string
          label: 'Parent field'
        reference_parent_by_uuid:
          type: boolean
          label: 'Reference parent by UUID instead of entity ID'
        arguments:
          type: sequence
          label: 'View arguments'
          sequence:
            type: string
            label: 'Argument'
