id: newreqnewpass_settings
label: Noreqnewpass configuration
migration_tags:
  - Drupal 7
  - Configuration
source:
  plugin: variable
  variables:
    - noreqnewpass_disabled
  source_module: noreqnewpass
process:
  'noreqnewpass_disable':
    plugin: default_value
    source: noreqnewpass_disabled
    default_value: TRUE
destination:
  plugin: config
  config_name: noreqnewpass.settings_form
